package ImpresionKidsCut;

public class Main { 
//	public static void main(String[] args){ 
////		Date date=new Date(); 
////		SimpleDateFormat fecha=new SimpleDateFormat("dd/MM/yyyy"); 
////		SimpleDateFormat hora=new SimpleDateFormat("hh:mm:ss aa"); 
//		PrintHandler.AddCabecera(PrintHandler.DibujarLinea(32));
//		PrintHandler.AddCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Codigo      : KCK6-G13-FA-004292");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Hr. Llegada  : 20:33:18");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Cliente     : Cecilia");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Ninio       : Eduardo");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Servicios y Personal");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Corte -> Humberto");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.DibujarLinea(32));
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.PrepararCorte());
//		PrintHandler.AddSubCabecera(PrintHandler.CortarPapel());
//		
////		Ticket.AddSubCabecera(Ticket.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.DibujarLinea(32));
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Codigo      : KCK6-G13-FA-004292");		
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Cliente      : Cecilia");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Ninio       : Eduardo");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Servicios y Personal");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Corte -> Humberto");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.DibujarLinea(32));
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.PrepararCorte());
//		PrintHandler.AddSubCabecera(PrintHandler.CortarPapel());
//		
////		Ticket.AddSubCabecera(Ticket.DarEspacio());
//		PrintHandler.AddSubCabecera("Bienvenido......");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("KidsCut : Sucursal K3");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.DibujarLinea(32));
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Codigo      : KCK6-G13-FA-004292");		
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera("Ninio       : Eduardo");
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.DibujarLinea(32));
//		PrintHandler.AddSubCabecera(PrintHandler.DarEspacio());
//		PrintHandler.AddSubCabecera(PrintHandler.PrepararCorte());
//		PrintHandler.AddSubCabecera(PrintHandler.CortarPapel());
//		PrintHandler.ImprimirDocumento();
//		
////		Ticket.AddCabecera("RESTAURANTE XXXX"); 
////		Ticket.AddCabecera(Ticket.DarEspacio()); 
////		Ticket.AddCabecera("EXPEDIDO EN: ----------"); 
////		Ticket.AddCabecera(Ticket.DarEspacio()); 
////		Ticket.AddCabecera("AV. TAMAULIPAS NO. 5 LOC. 101"); 
////		Ticket.AddCabecera(Ticket.DarEspacio()); 
////		Ticket.AddCabecera(Ticket.DibujarLinea(29)); 
////		Ticket.AddCabecera(Ticket.DarEspacio()); 
////		Ticket.AddCabecera("LIMA, XXXXXXXXXXXX"); 
////		Ticket.AddCabecera(Ticket.DarEspacio()); 
////		Ticket.AddCabecera("RFC: CSI-020226-MV4"); 
////		Ticket.AddCabecera(Ticket.DarEspacio()); 
////		Ticket.AddSubCabecera(Ticket.DarEspacio()); 
////		Ticket.AddSubCabecera("Caja # 1 - Ticket # 1"); 
////		Ticket.AddSubCabecera(Ticket.DarEspacio()); 
////		Ticket.AddSubCabecera("LE ATENDIO: JUAN"); 
////		Ticket.AddSubCabecera(Ticket.DarEspacio()); 
////		Ticket.AddSubCabecera(""+fecha.format(date) + " " + hora.format(date)); 
////		Ticket.AddSubCabecera(Ticket.DarEspacio()); 
////		Ticket.AddSubCabecera(Ticket.DibujarLinea(29)); 
////		Ticket.AddSubCabecera(Ticket.DarEspacio()); 
////		Ticket.AddItem("1","Articulo Prueba","15.00"); 
////		Ticket.AddItem("","",Ticket.DarEspacio()); 
////		Ticket.AddItem("2","Articulo Prueba","25.00"); 
////		Ticket.AddItem("","",Ticket.DarEspacio()); 
////		Ticket.AddTotal("",Ticket.DibujarLinea(29)); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("SUBTOTAL","29.75"); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("IVA","5.25"); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("TOTAL","35.00"); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("RECIBIDO","50.00"); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("CAMBIO","15.00"); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddTotal("",Ticket.DarEspacio()); 
////		Ticket.AddPieLinea(Ticket.DibujarLinea(29)); 
////		Ticket.AddPieLinea(Ticket.DarEspacio()); 
////		Ticket.AddPieLinea("EL xxx ES NUESTRA PASION..."); 
////		Ticket.AddPieLinea(Ticket.DarEspacio()); 
////		Ticket.AddPieLinea("VIVE LA EXPERIENCIA EN xxx"); 
////		Ticket.AddPieLinea(Ticket.DarEspacio()); 
////		Ticket.AddPieLinea("Gracias por su visita"); 
////		Ticket.AddPieLinea(Ticket.DarEspacio());
////		Ticket.AddPieLinea(Ticket.PrepararCorte());
////		Ticket.AddPieLinea(Ticket.CortarPapel());		
////		Ticket.ImprimirDocumento(); 
//	} 
} 